### ISSUE TITLE
AbstractMethodError

### ISSUE THREAD

**Issue by lucgirardin** [wolfie/HistoryExtension#1]
I occasionally get the following exception when using Vaadin 7.4.0, especially when hitting the back button: 

`java.lang.AbstractMethodError: com.github.wolfie.history.HistoryExtension$1.call(Lelemental/json/JsonArray;)V
    at com.vaadin.server.JavaScriptCallbackHelper$1.call(JavaScriptCallbackHelper.java:80)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at com.vaadin.server.ServerRpcManager.applyInvocation(ServerRpcManager.java:168)
    at com.vaadin.server.ServerRpcManager.applyInvocation(ServerRpcManager.java:118)
    at com.vaadin.server.communication.ServerRpcHandler.handleInvocations(ServerRpcHandler.java:291)
    at com.vaadin.server.communication.ServerRpcHandler.handleRpc(ServerRpcHandler.java:184)
    at com.vaadin.server.communication.UidlRequestHandler.synchronizedHandleRequest(UidlRequestHandler.java:92)
    at com.vaadin.server.SynchronizedRequestHandler.handleRequest(SynchronizedRequestHandler.java:41)
    at com.vaadin.server.VaadinService.handleRequest(VaadinService.java:1408)
    at com.vaadin.server.VaadinServlet.service(VaadinServlet.java:350)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:727)
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
    at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
    at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:220)
    at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:122)
    at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:501)
    at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:170)
    at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:98)
    at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:950)
    at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
    at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:408)
    at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1040)
    at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:607)
    at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:315)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)`

**Comment by wolfie** [comment]
It might be related to the fact that Vaadin 7.4.0 changed the JSON library,
and something might've become incompatible. I'll see if I can make a
compatible version at some point. I'm quite busy at work currently, so I
can't suggest holding your breath :(

On Mon, Mar 2, 2015 at 2:01 AM, lucgirardin notifications@github.com
wrote:

> I occasionally get the following exception when using Vaadin 7.4.0,
> especially when hitting the back button:
> 
> java.lang.AbstractMethodError:
> com.github.wolfie.history.HistoryExtension$1.call(Lelemental/json/JsonArray;)V
> at
> com.vaadin.server.JavaScriptCallbackHelper$1.call(JavaScriptCallbackHelper.java:80)
> at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> at
> sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> at
> sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> at java.lang.reflect.Method.invoke(Method.java:483)
> at
> com.vaadin.server.ServerRpcManager.applyInvocation(ServerRpcManager.java:168)
> at
> com.vaadin.server.ServerRpcManager.applyInvocation(ServerRpcManager.java:118)
> at
> com.vaadin.server.communication.ServerRpcHandler.handleInvocations(ServerRpcHandler.java:291)
> at
> com.vaadin.server.communication.ServerRpcHandler.handleRpc(ServerRpcHandler.java:184)
> at
> com.vaadin.server.communication.UidlRequestHandler.synchronizedHandleRequest(UidlRequestHandler.java:92)
> at
> com.vaadin.server.SynchronizedRequestHandler.handleRequest(SynchronizedRequestHandler.java:41)
> at com.vaadin.server.VaadinService.handleRequest(VaadinService.java:1408)
> at com.vaadin.server.VaadinServlet.service(VaadinServlet.java:350)
> at javax.servlet.http.HttpServlet.service(HttpServlet.java:727)
> at
> org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)
> at
> org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
> at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
> at
> org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
> at
> org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
> at
> org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:220)
> at
> org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:122)
> at
> org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:501)
> at
> org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:170)
> at
> org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:98)
> at
> org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:950)
> at
> org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
> at
> org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:408)
> at
> org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1040)
> at
> org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:607)
> at
> org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:315)
> at
> java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
> at
> java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
> at java.lang.Thread.run(Thread.java:745)
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/wolfie/HistoryExtension/issues/1.

## 

Henrik Paul

**Comment by lucgirardin** [comment]
Many thanks for the quick reply! I should be able to find some time to fix it myself in the next few days. It would simplify things if you could provide the build.xml file, as I am unable to compile the current code because of a weird error:
`[javac] /Users/luc/java/HistoryExtension/src/com/github/wolfie/history/HistoryExtension.java:17: error: package com.sun.xml.internal.txw2 does not exist
    [javac] import com.sun.xml.internal.txw2.IllegalAnnotationException;`

**Comment by wolfie** [comment]
Whoa. That's a huge mistake on my part.
https://github.com/wolfie/HistoryExtension/blob/master/src/com/github/wolfie/history/HistoryExtension.java#L561
seems to throw an IllegalAnnotationException, when it should throw an
IllegalArgumentException.

On Tue, Mar 3, 2015 at 1:43 PM, lucgirardin notifications@github.com
wrote:

> Many thanks for the quick reply! I should be able to find some time to fix
> it myself in the next few days. It would simplify things if you could
> provide the build.xml file, as I am unable to compile the current code
> because of a weird error:
> [javac]
> /Users/luc/java/HistoryExtension/src/com/github/wolfie/history/HistoryExtension.java:17:
> error: package com.sun.xml.internal.txw2 does not exist
> [javac] import com.sun.xml.internal.txw2.IllegalAnnotationException;
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/wolfie/HistoryExtension/issues/1#issuecomment-76930943
> .

## 

Henrik Paul

**Comment by lucgirardin** [comment]
Then, as soon as you change the Vaadin version to 7.4.0 in ivy.xml, you get these additional compilation error:

`[javac] /Users/luc/java/HistoryExtension/src/com/github/wolfie/history/HistoryExtension.java:12: error: package org.json does not exist
    [javac] import org.json.JSONArray;
    [javac]                ^
    [javac] /Users/luc/java/HistoryExtension/src/com/github/wolfie/history/HistoryExtension.java:13: error: package org.json does not exist
    [javac] import org.json.JSONException;
    [javac]                ^
    [javac] /Users/luc/java/HistoryExtension/src/com/github/wolfie/history/HistoryExtension.java:14: error: package org.json does not exist
    [javac] import org.json.JSONObject;`

Did Vaadin change its JSON library?!?

**Comment by wolfie** [comment]
Yes, as I said, 7.4.0 changed the JSON library. http://vaadin.com/download/release/7.4/7.4.0/release-notes.html#incompatible

**Comment by lucgirardin** [comment]
I fixed the compatibility with Vaadin 7.4.0 and 7.4.1 and you can find my changes in my fork of the project (https://github.com/lucgirardin/HistoryExtension). There is a bug in how Map are converted to JSON with the current version of Vaadin (because of generics) and I therefore opted for a solution with JsonArray of pair of String for key/value. Should probably report this issue to the Vaadin team. Should you have the time and inclination, I think it would be good to publish that update to the Vaadin Add-ons directory. Enjoy!

**Comment by wolfie** [comment]
Oh wow. Thank you SO much. I'll try to find the time (and actually
remember) to check your patch and merge it in. ^_^ Have a great
wait-for-summer (assuming you're in the northern hemisphere. Otherwise,
have a nice winter :P )

On Wed, Mar 11, 2015 at 4:30 PM, lucgirardin notifications@github.com
wrote:

> I fixed the compatibility with Vaadin 7.4.0 and 7.4.1 and you can find my
> changes in my fork of the project (
> https://github.com/lucgirardin/HistoryExtension). There is a bug in how
> Map are converted to JSON with the current version of Vaadin (because of
> generics) and I therefore opted for a solution with JsonArray of pair of
> String for key/value. Should probably report this issue to the Vaadin team.
> Should you have the time and inclination, I think it would be good to
> publish that update to the Vaadin Add-ons directory. Enjoy!
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/wolfie/HistoryExtension/issues/1#issuecomment-78273655
> .

## 

Henrik Paul

**Comment by bitbrain** [comment]
Issue still exists. When does the merge come?

**Comment by wolfie** [comment]
Oh, yeah, sorry. I actually took a quick look on the code, and, from what I
remember, there were some things (code specific to your needs) that i
didn't prefer to have in my repository. Since it was not a pull request, i
didn't find a suitable venue to comment on the changes, so I kind of didn't
do anything about it and let it be

On Mon, Apr 20, 2015 at 10:28 AM, Miguel Gonzalez notifications@github.com
wrote:

> Issue still exists. When does the merge come?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/wolfie/HistoryExtension/issues/1#issuecomment-94379637
> .

## 

Henrik Paul

**Comment by aberresch** [comment]
Hi,

could you provide your build.xml?

**Comment by wolfie** [comment]
There is none. I just use the Vaadin plugin for Eclipse to export to add-on

**Comment by lucgirardin** [comment]
I finally created a pull request, hoping that it will make it easy for you to integrate!

**Comment by wolfie** [comment]
Thanks man. I'll take a look this weekend. Sorry for being such a lazy
bastard :)

On Wed, Oct 21, 2015 at 1:34 AM, Luc Girardin notifications@github.com
wrote:

> I finally created a pull request, hoping that it will make it easy for you
> to integrate!
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/wolfie/HistoryExtension/issues/1#issuecomment-149721971
> .

## 

Henrik Paul

**Comment by lucgirardin** [comment]
The ultimate laziness is to give away committer rights to the repository and head back to the beach ;-)
